import arcpy
fl = arcpy.GetParameterAsText(0)
arcpy.AddMessage("Selecting inland points")
arcpy.SelectLayerByLocation_management(fl,"INTERSECT",r"E:\cottaan\My Documents\ArcGIS\Google Earth Engine Downloads\sampleValidationSites.gdb\esri_countries")
arcpy.AddMessage("Updating inland points")
arcpy.CalculateField_management(fl,"waterclass","'Inland'","PYTHON_9.3")
arcpy.AddMessage("Selecting coastal points")
arcpy.SelectLayerByLocation_management(fl,"INTERSECT",r"E:\cottaan\My Documents\ArcGIS\Google Earth Engine Downloads\sampleValidationSites.gdb\coastal_buffer_500m")
arcpy.AddMessage("Updating coastal points")
arcpy.CalculateField_management(fl,"waterclass","'Coastal'","PYTHON_9.3")
arcpy.AddMessage("Selecting marine points")
arcpy.SelectLayerByAttribute_management(fl,"NEW_SELECTION","waterclass IS NULL")
arcpy.AddMessage("Updating marine points")
arcpy.CalculateField_management(fl,"waterclass","'Marine'","PYTHON_9.3")
